### ISSUE TITLE
UnicodeEncodeError in tree.write(f, encoding='unicode')

### ISSUE THREAD

**Issue by quantum-hash** [JHMeusener/CarlaSimpleXODRProjectionWorkaround#3]
Traceback (most recent call last):
  File "main.py", line 94, in <module>
    tree.write(f, encoding='unicode')

  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python37\lib\xml\etree\ElementTree.py", line 935, in _serialize_xml
    write(" %s=\"%s\"" % (qnames[k], v))
    
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2194' in position 41: character maps to <undefined>

**Comment by quantum-hash** [comment]
Solved with this change (by using a supported encoding like 'utf-8) : 

```python
with open(newOSMLocation, 'w', encoding='utf-8') as f:
    tree.write(f, encoding='unicode')
```


Instead of :

```python
with open(newOSMLocation, 'w') as f:
    tree.write(f, encoding='unicode')
```
